# WARNING: CAKEFILE IS SHIT
# Please make it better for other people to use

{exec} = require 'child_process'
{ncp}  = require 'ncp'
 
task "sbuild", "build the files", (options) ->
	exec "coffee --compile --output build/js/ src/"
	exec "cson2json src/manifest.cson > build/manifest.json"
	ncp "src/misc/", "build/", ->
		console.log "Copied"

task "watch", "watch for changes and build the files", (options) ->
	exec "coffee --watch --compile --output build/js/ src/"
